### ISSUE TITLE
Reduce the worflow run on PR close

### ISSUE THREAD

**Issue by Eomm** [nearform/optic-release-automation-action#81]
Starting from this PR https://github.com/fastify/fastify-accepts/pull/123
The `on:` parameter could filter unnecessary workflow runs:

```
  pull_request:
    types: [closed]
    branches:
      - main
      - master
      - 'release/**'
```

Does it worth documenting it?
